### ISSUE TITLE
latest changes are not committed to m.98 python ticketing project !

### ISSUE THREAD

**Issue by AradArvin** [mohammadT77/m98_event#1]
hi I'm Alireza Arvin from m.98 python and I was trying to get the code from your git but it seems the latest changes from the ticketing project were not committed to the code. like **_main_actions.py_** --> (its empty). and I'm not sure if other files are updated or not. please take a look and fix this issue.

#documentation 
#enhancement
ticketing/main_actions.py

**Comment by amin-tehrani** [comment]
sorry for that.
Done!

**Comment by AradArvin** [comment]
Thanks for fixing the problem : )
